name: Build Back-End

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string
      environment:
        required: true
        type: string
        default: "pr-validate"
      artifact_name:
        required: true
        type: string
        default: "build-artifact"

jobs:
  backend_linting:
    name: Backend Code Quality
    runs-on: ubuntu-latest
    environment: pr-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Backend Dependencies
        run: echo "Installing backend dependencies..."

  backend_build:
    name: backend Build
    runs-on: ubuntu-latest
    needs: backend_linting
    environment: pr-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install backend Dependencies
        run: echo "Installing backend dependencies..."

  backend_unit_tests:
    name: backend Unit Tests
    runs-on: ubuntu-latest
    needs: backend_build
    environment: pr-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install backend Dependencies
        run: echo "Installing backend dependencies..."

  backend_veracode_scan:
    name: backend Veracode scan
    runs-on: ubuntu-latest
    needs: backend_build
    environment: pr-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install backend Dependencies
        run: echo "Installing backend dependencies..."

  upload_be_artifact:
    name: upload Back-End Artifact
    runs-on: ubuntu-latest
    environment: pr-validate
    needs: [backend_unit_tests, backend_veracode_scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload BE Artifact
        run: echo "Installing backend dependencies..."
